CREATE TABLE "MATERIAL" 
(
	"ID"	 	INTEGER NOT NULL,
	"NOME"		VARCHAR(30) NOT NULL,
	"DESCRICAO"	VARCHAR(255) NOT NULL,
	"OBSERVACOES"	VARCHAR(255),
	PRIMARY KEY ("ID")
);

CREATE TABLE "LOTE" 
(
	"ID"		INTEGER NOT NULL ,
	"TEMPO"		SMALLINT NOT NULL,
	"QUANTIDADE"	INTEGER NOT NULL,
	PRIMARY KEY ("ID")
); 

CREATE TABLE "OL" 
(
	"ID"	 	INTEGER NOT NULL ,
	"MATERIAL_ID"	INTEGER NOT NULL,
	PRIMARY KEY ("ID")
);

CREATE TABLE "LOTE_OL"
(
	"OL_ID"		INTEGER NOT NULL,
	"LOTE_ID"	INTEGER NOT NULL,
	PRIMARY KEY ("OL_ID", "LOTE_ID")
);


CREATE TABLE "PROGRAMACAO"
(
	"ID"	 		INTEGER NOT NULL ,
	"DESCRICAO"		VARCHAR(255), 	
	"UNIDADEDETEMPO"	SMALLINT NOT NULL,
	"TEMPOINICIAL"		SMALLINT NOT NULL,
	"TEMPOFINAL"		SMALLINT NOT NULL,
	PRIMARY KEY ("ID"),
	CHECK ("TEMPOFINAL" >= "TEMPOINICIAL")
);


CREATE TABLE "PROGRAMACAO_OL"
(
	"PROGRAMACAO_ID"	INTEGER NOT NULL,
	"OL_ID"			INTEGER NOT NULL,
	PRIMARY KEY ("PROGRAMACAO_ID", "OL_ID")
);

ALTER TABLE "OL" ADD FOREIGN KEY ("MATERIAL_ID") REFERENCES "MATERIAL"("ID");
ALTER TABLE "LOTE_OL" ADD FOREIGN KEY ("OL_ID") REFERENCES "OL"("ID");
ALTER TABLE "LOTE_OL" ADD FOREIGN KEY ("LOTE_ID") REFERENCES "LOTE"("ID");
ALTER TABLE "PROGRAMACAO_OL" ADD FOREIGN KEY ("PROGRAMACAO_ID") REFERENCES "PROGRAMACAO"("ID");
ALTER TABLE "PROGRAMACAO_OL" ADD FOREIGN KEY ("OL_ID") REFERENCES "OL"("ID");


CREATE GENERATOR "MATERIAL_ID";
CREATE GENERATOR "OL_ID";
CREATE GENERATOR "LOTE_ID";
CREATE GENERATOR "PROGRAMACAO_ID";


SET TERM ^ ;
CREATE TRIGGER "MATERIAL_AUTOID" FOR "MATERIAL" 
ACTIVE BEFORE INSERT POSITION 0
AS
	BEGIN
		NEW.ID = GEN_ID(MATERIAL_ID, 1);
	END
^

CREATE TRIGGER "OL_AUTOID" FOR "OL" 
ACTIVE BEFORE INSERT POSITION 0
AS
	BEGIN
		NEW.ID = GEN_ID(OL_ID, 1);
	END
^


CREATE TRIGGER "LOTE_AUTOID" FOR "LOTE" 
ACTIVE BEFORE INSERT POSITION 0
AS
	BEGIN
		NEW.ID = GEN_ID(LOTE_ID, 1);
	END
^

CREATE TRIGGER "PROGRAMACAO_AUTOID" FOR "PROGRAMACAO" 
ACTIVE BEFORE INSERT POSITION 0
AS
	BEGIN
		NEW.ID = GEN_ID(PROGRAMACAO_ID, 1);
	END
^

SET TERM ; ^
